from clinv.sources.aws import \
    EC2src, \
    IAMUsersrc,\
    IAMGroupsrc, \
    Route53src, \
    RDSsrc, \
    S3src
from clinv.sources.aws import EC2, RDS, Route53, S3, IAMUser, IAMGroup
from dateutil.tz import tzutc
from unittest.mock import patch, call, PropertyMock
from tests.sources import ClinvSourceBaseTestClass, ClinvGenericResourceTests
import datetime
import unittest


class AWSSourceBaseTestClass(ClinvSourceBaseTestClass):
    '''
    Abstract Base class to ensure that all the AWS sources have the same
    interface.

    Must be combined with a unittest.TestCase that defines:
        * self.source_obj the name of the source class to test
        * self.module_name: the name of the module file
    '''

    def setUp(self):
        self.module_name = 'aws'
        super().setUp()
        self.boto_patch = patch('clinv.sources.aws.boto3', autospect=True)
        self.boto = self.boto_patch.start()

    def tearDown(self):
        super().tearDown()
        self.boto_patch.stop()

    def test_get_regions(self):
        self.boto.client.return_value.describe_regions.return_value = {
            'Regions': [
                {
                    'RegionName': 'us-east-1'
                },
                {
                    'RegionName': 'eu-west-1'
                },
            ]
        }
        self.assertEqual(self.src.regions, ['us-east-1', 'eu-west-1'])


class TestEC2Source(AWSSourceBaseTestClass, unittest.TestCase):
    '''
    Test the EC2 implementation in the inventory.
    '''

    def setUp(self):
        super().setUp()
        self.source_obj = EC2src

        # Initialize object to test
        source_data = {}
        user_data = {}
        self.src = self.source_obj(source_data, user_data)

        # Expected source_data dictionary generated by generate_source_data
        self.desired_source_data = {
            'us-east-1': [
                {
                    'Groups': [],
                    'Instances': [
                        {
                            'ImageId': 'ami-ffcsssss',
                            'InstanceId': 'i-023desldk394995ss',
                            'InstanceType': 'c4.4xlarge',
                            'LaunchTime': datetime.datetime(
                                2018, 5, 10, 7, 13, 17, tzinfo=tzutc()
                            ),
                            'NetworkInterfaces': [
                                {
                                    'PrivateIpAddresses': [
                                        {
                                            'Association': {
                                                'IpOwnerId': '585394460090',
                                                'PublicDnsName': 'ec2.com',
                                                'PublicIp': '32.312.444.22'
                                            },
                                            'Primary': True,
                                            'PrivateDnsName': 'ec2.nternal',
                                            'PrivateIpAddress': '1.1.1.1',
                                        }
                                    ],
                                }
                            ],
                            'SecurityGroups': [
                                {
                                    'GroupId': 'sg-f2234gf6',
                                    'GroupName': 'sg-1'
                                },
                                {
                                    'GroupId': 'sg-cwfccs17',
                                    'GroupName': 'sg-2'
                                }
                            ],
                            'State': {'Code': 16, 'Name': 'running'},
                            'StateTransitionReason': '',
                            'Tags': [{'Key': 'Name', 'Value': 'name'}],
                            'VpcId': 'vpc-31084921'
                        }
                    ],
                    'OwnerId': '585394460090',
                    'ReservationId': 'r-039ed99cad2bb3da5'
                },
            ],
        }
        self.desired_user_data = {
            'i-023desldk394995ss': {
                'description': '',
                'to_destroy': 'tbd',
                'environment': 'tbd',
                'region': 'us-east-1',
            },
        }

        self.src.source_data = self.desired_source_data

    def tearDown(self):
        super().tearDown()

    @patch('clinv.sources.aws.EC2src.regions', new_callable=PropertyMock)
    def test_generate_source_data_creates_expected_source_data_attrib(
        self,
        regionsMock
    ):
        regionsMock.return_value = ['us-east-1']
        self.boto.client.return_value.describe_instances.return_value = {
            'Reservations': [
                {
                    'Groups': [],
                    'Instances': [
                        {
                            'AmiLaunchIndex': 0,
                            'Architecture': 'x86_64',
                            'BlockDeviceMappings': [
                                {
                                    'DeviceName': '/dev/sda1',
                                    'Ebs': {
                                        'AttachTime': datetime.datetime(
                                            2018, 5, 10, 2, 58, 4,
                                            tzinfo=tzutc()
                                        ),
                                        'DeleteOnTermination': True,
                                        'Status': 'attached',
                                        'VolumeId': 'vol-02257f9299430042f'
                                    }
                                }
                            ],
                            'CapacityReservationSpecification': {
                                'CapacityReservationPreference': 'open'
                            },
                            'ClientToken': '',
                            'CpuOptions': {
                                'CoreCount': 8,
                                'ThreadsPerCore': 2
                            },
                            'EbsOptimized': True,
                            'HibernationOptions': {'Configured': False},
                            'Hypervisor': 'xen',
                            'ImageId': 'ami-ffcsssss',
                            'InstanceId': 'i-023desldk394995ss',
                            'InstanceType': 'c4.4xlarge',
                            'KeyName': 'ssh_keypair',
                            'LaunchTime': datetime.datetime(
                                2018, 5, 10, 7, 13, 17, tzinfo=tzutc()
                            ),
                            'Monitoring': {'State': 'enabled'},
                            'NetworkInterfaces': [
                                {
                                    'Association': {
                                        'IpOwnerId': '585394229490',
                                        'PublicDnsName': 'ec21.amazonaws.com',
                                        'PublicIp': '32.312.444.22'
                                    },
                                    'Attachment': {
                                        'AttachTime': datetime.datetime(
                                            2018, 5, 10, 2, 58, 3,
                                            tzinfo=tzutc()
                                        ),
                                        'AttachmentId': 'eni-attach-032346',
                                        'DeleteOnTermination': True,
                                        'DeviceIndex': 0,
                                        'Status': 'attached'
                                    },
                                    'Description': 'Primary ni',
                                    'Groups': [
                                        {
                                            'GroupId': 'sg-f2234gf6',
                                            'GroupName': 'sg-1'
                                        },
                                        {
                                            'GroupId': 'sg-cwfccs17',
                                            'GroupName': 'sg-2'
                                        }
                                    ],
                                    'InterfaceType': 'interface',
                                    'Ipv6Addresses': [],
                                    'MacAddress': '0a:ff:ff:ff:ff:aa',
                                    'NetworkInterfaceId': 'eni-3fssaw0a',
                                    'OwnerId': '583949112399',
                                    'PrivateDnsName': 'ip-112.ec2.internal',
                                    'PrivateIpAddress': '142.33.2.113',
                                    'PrivateIpAddresses': [
                                        {
                                            'Association': {
                                                'IpOwnerId': '585394460090',
                                                'PublicDnsName': 'ec2.com',
                                                'PublicIp': '32.312.444.22'
                                            },
                                            'Primary': True,
                                            'PrivateDnsName': 'ec2.nternal',
                                            'PrivateIpAddress': '1.1.1.1',
                                        }
                                    ],
                                    'SourceDestCheck': True,
                                    'Status': 'in-use',
                                    'SubnetId': 'subnet-3ssaafs1',
                                    'VpcId': 'vpc-fs12f872'
                                }
                            ],
                            'Placement': {
                                'AvailabilityZone': 'eu-east-1a',
                                'GroupName': '',
                                'Tenancy': 'default'
                            },
                            'PrivateDnsName': 'ip-112.ec2.internal',
                            'PrivateIpAddress': '142.33.2.113',
                            'ProductCodes': [],
                            'PublicDnsName': 'ec2.com',
                            'PublicIpAddress': '32.312.444.22',
                            'RootDeviceName': '/dev/sda1',
                            'RootDeviceType': 'ebs',
                            'SecurityGroups': [
                                {
                                    'GroupId': 'sg-f2234gf6',
                                    'GroupName': 'sg-1'
                                },
                                {
                                    'GroupId': 'sg-cwfccs17',
                                    'GroupName': 'sg-2'
                                }
                            ],
                            'SourceDestCheck': True,
                            'State': {'Code': 16, 'Name': 'running'},
                            'StateTransitionReason': '',
                            'SubnetId': 'subnet-sfsdwf12',
                            'Tags': [{'Key': 'Name', 'Value': 'name'}],
                            'VirtualizationType': 'hvm',
                            'VpcId': 'vpc-31084921'
                        }
                    ],
                    'OwnerId': '585394460090',
                    'ReservationId': 'r-039ed99cad2bb3da5'
                }
            ]
        }

        self.src.source_data = {}

        generated_source_data = self.src.generate_source_data()
        self.assertEqual(
            self.src.source_data,
            self.desired_source_data,
        )
        self.assertEqual(
            generated_source_data,
            self.desired_source_data,
        )

    def test_generate_user_data_creates_empty_user_data_if_no_src_data(self):
        self.src.source_data = {'us-east-1': {}}
        self.src.generate_user_data()
        self.assertEqual(self.src.user_data, {})

    def test_generate_user_data_adds_desired_default_user_data(self):
        self.src.generate_user_data()

        self.assertEqual(
            self.src.user_data,
            self.desired_user_data,
        )

    def test_generate_user_data_doesnt_loose_existing_data(self):
        desired_user_data = {
            'i-023desldk394995ss': {
                'description': 'filled description',
                'to_destroy': False,
                'environment': 'production',
                'region': 'us-east-1',
            },
        }

        self.src.user_data = desired_user_data

        self.src.generate_user_data()

        self.assertEqual(
            self.src.user_data,
            desired_user_data,
        )

    def test_generate_user_data_creates_expected_user_data_attrib(self):
        expected_user_data = {}

        generated_user_data = self.src.generate_source_data()

        self.assertEqual(
            self.src.user_data,
            expected_user_data,
        )
        self.assertEqual(
            generated_user_data,
            expected_user_data,
        )

    def test_generate_inventory_return_empty_dict_if_no_data(self):
        self.src.source_data = {'hosted_zones': {}}
        self.assertEqual(self.src.generate_inventory(), {})

    @patch('clinv.sources.aws.EC2')
    def test_generate_inventory_creates_expected_dictionary(
        self,
        resource_mock
    ):
        resource_id = 'i-023desldk394995ss'
        self.src.user_data = {
            'i-023desldk394995ss': {
                'description': 'tbd',
                'to_destroy': 'tbd',
                'environment': 'tbd',
                'region': 'us-east-1',
            },
        }

        desired_mock_input = {
            **self.src.user_data['i-023desldk394995ss'],
            **self.src.source_data['us-east-1'][0]['Instances'][0],
        }

        desired_inventory = self.src.generate_inventory()
        self.assertEqual(
            resource_mock.assert_called_with(
                {
                    resource_id: desired_mock_input
                },
            ),
            None,
        )

        self.assertEqual(
            desired_inventory,
            {
                resource_id: resource_mock.return_value
            },
        )


class TestRDSSource(AWSSourceBaseTestClass, unittest.TestCase):
    '''
    Test the RDS implementation in the inventory.
    '''

    def setUp(self):
        super().setUp()
        self.source_obj = RDSsrc

        # Initialize object to test
        source_data = {}
        user_data = {}
        self.src = self.source_obj(source_data, user_data)

        # Expected source_data dictionary generated by generate_source_data
        self.desired_source_data = {
            'us-east-1': [
                {
                    'AllocatedStorage': 100,
                    'AssociatedRoles': [],
                    'AutoMinorVersionUpgrade': True,
                    'AvailabilityZone': 'us-east-1a',
                    'BackupRetentionPeriod': 7,
                    'CACertificateIdentifier': 'rds-ca-2015',
                    'DBInstanceArn': 'arn:aws:rds:us-east-1:224119285:db:db',
                    'DBInstanceClass': 'db.t2.micro',
                    'DBInstanceIdentifier': 'rds-name',
                    'DBInstanceStatus': 'available',
                    'DBSecurityGroups': [],
                    'DBSubnetGroup': {
                        'DBSubnetGroupDescription': 'Created from the RDS '
                        'Management Console',
                        'DBSubnetGroupName': 'default-vpc-v2dcp2jh',
                        'SubnetGroupStatus': 'Complete',
                        'Subnets': [
                            {
                                'SubnetAvailabilityZone': {
                                    'Name': 'us-east-1a'
                                },
                                'SubnetIdentifier': 'subnet-42sfl222',
                                'SubnetStatus': 'Active'
                            },
                            {
                                'SubnetAvailabilityZone': {
                                    'Name': 'us-east-1e'
                                },
                                'SubnetIdentifier': 'subnet-42sfl221',
                                'SubnetStatus': 'Active'
                            },
                        ],
                        'VpcId': 'vpc-v2dcp2jh'},
                    'DbiResourceId': 'db-YDFL2',
                    'DeletionProtection': True,
                    'Endpoint': {
                        'Address': 'rds-name.us-east-1.rds.amazonaws.com',
                        'HostedZoneId': '202FGHSL2JKCFW',
                        'Port': 5521
                    },
                    'Engine': 'mariadb',
                    'EngineVersion': '1.2',
                    'InstanceCreateTime': datetime.datetime(
                        2019, 6, 17, 15, 15, 8, 461000, tzinfo=tzutc()
                    ),
                    'Iops': 1000,
                    'MasterUsername': 'root',
                    'MultiAZ': True,
                    'PreferredBackupWindow': '03:00-04:00',
                    'PreferredMaintenanceWindow': 'fri:04:00-fri:05:00',
                    'PubliclyAccessible': False,
                    'StorageEncrypted': True,
                },
            ],
        }
        self.desired_user_data = {
            'db-YDFL2': {
                'description': '',
                'to_destroy': 'tbd',
                'environment': 'tbd',
                'region': 'us-east-1',
            },
        }

        self.src.source_data = self.desired_source_data

    def tearDown(self):
        super().tearDown()

    @patch('clinv.sources.aws.RDSsrc.regions', new_callable=PropertyMock)
    def test_generate_source_data_creates_expected_source_data_attrib(
        self,
        regionsMock
    ):
        regionsMock.return_value = ['us-east-1']
        self.boto.client.return_value.describe_db_instances.return_value = {
            'DBInstances': [
                {
                    'AllocatedStorage': 100,
                    'AssociatedRoles': [],
                    'AutoMinorVersionUpgrade': True,
                    'AvailabilityZone': 'us-east-1a',
                    'BackupRetentionPeriod': 7,
                    'CACertificateIdentifier': 'rds-ca-2015',
                    'CopyTagsToSnapshot': True,
                    'DBInstanceArn': 'arn:aws:rds:us-east-1:224119285:db:db',
                    'DBInstanceClass': 'db.t2.micro',
                    'DBInstanceIdentifier': 'rds-name',
                    'DBInstanceStatus': 'available',
                    'DBParameterGroups': [
                        {
                            'DBParameterGroupName': 'default.postgres11',
                            'ParameterApplyStatus': 'in-sync'
                        }
                    ],
                    'DBSecurityGroups': [],
                    'DBSubnetGroup': {
                        'DBSubnetGroupDescription': 'Created from the RDS '
                        'Management Console',
                        'DBSubnetGroupName': 'default-vpc-v2dcp2jh',
                        'SubnetGroupStatus': 'Complete',
                        'Subnets': [
                            {
                                'SubnetAvailabilityZone': {
                                    'Name': 'us-east-1a'
                                },
                                'SubnetIdentifier': 'subnet-42sfl222',
                                'SubnetStatus': 'Active'
                            },
                            {
                                'SubnetAvailabilityZone': {
                                    'Name': 'us-east-1e'
                                },
                                'SubnetIdentifier': 'subnet-42sfl221',
                                'SubnetStatus': 'Active'
                            },
                        ],
                        'VpcId': 'vpc-v2dcp2jh'},
                    'DbInstancePort': 0,
                    'DbiResourceId': 'db-YDFL2',
                    'DeletionProtection': True,
                    'DomainMemberships': [],
                    'Endpoint': {
                        'Address': 'rds-name.us-east-1.rds.amazonaws.com',
                        'HostedZoneId': '202FGHSL2JKCFW',
                        'Port': 5521
                    },
                    'Engine': 'mariadb',
                    'EngineVersion': '1.2',
                    'EnhancedMonitoringResourceArn': 'logs-arn',
                    'IAMDatabaseAuthenticationEnabled': False,
                    'InstanceCreateTime': datetime.datetime(
                        2019, 6, 17, 15, 15, 8, 461000, tzinfo=tzutc()
                    ),
                    'Iops': 1000,
                    'LatestRestorableTime': datetime.datetime(
                        2019, 7, 8, 6, 23, 55, tzinfo=tzutc()
                    ),
                    'LicenseModel': 'mariadb-license',
                    'MasterUsername': 'root',
                    'MonitoringInterval': 60,
                    'MonitoringRoleArn': 'monitoring-arn',
                    'MultiAZ': True,
                    'OptionGroupMemberships': [
                        {
                            'OptionGroupName': 'default:mariadb-1',
                            'Status': 'in-sync'
                        }
                    ],
                    'PendingModifiedValues': {},
                    'PerformanceInsightsEnabled': True,
                    'PerformanceInsightsKMSKeyId': 'performance-arn',
                    'PerformanceInsightsRetentionPeriod': 7,
                    'PreferredBackupWindow': '03:00-04:00',
                    'PreferredMaintenanceWindow': 'fri:04:00-fri:05:00',
                    'PubliclyAccessible': False,
                    'ReadReplicaDBInstanceIdentifiers': [],
                    'StorageEncrypted': True,
                    'StorageType': 'io1',
                    'VpcSecurityGroups': [
                        {
                            'Status': 'active',
                            'VpcSecurityGroupId': 'sg-f23le20g'
                        },
                    ],
                },
            ],
        }

        self.src.source_data = {}
        generated_source_data = self.src.generate_source_data()
        self.assertEqual(
            self.src.source_data,
            self.desired_source_data,
        )
        self.assertEqual(
            generated_source_data,
            self.desired_source_data,
        )

    def test_generate_user_data_creates_empty_user_data_if_no_src_data(self):
        self.src.source_data = {'us-east-1': {}}
        self.src.generate_user_data()
        self.assertEqual(self.src.user_data, {})

    def test_generate_user_data_adds_desired_default_user_data(self):
        generated_user_data = self.src.generate_user_data()

        self.assertEqual(
            self.src.user_data,
            self.desired_user_data,
        )
        self.assertEqual(
            generated_user_data,
            self.desired_user_data,
        )

    def test_generate_inventory_return_empty_dict_if_no_data(self):
        self.src.source_data = {'hosted_zones': {}}
        self.assertEqual(self.src.generate_inventory(), {})

    @patch('clinv.sources.aws.RDS')
    def test_generate_inventory_creates_expected_dictionary(
        self,
        resource_mock
    ):
        resource_id = 'db-YDFL2'
        self.src.user_data = {
            'db-YDFL2': {
                'description': 'tbd',
                'to_destroy': 'tbd',
                'environment': 'tbd',
                'region': 'us-east-1',
            },
        }

        desired_mock_input = {
            **self.src.user_data['db-YDFL2'],
            **self.src.source_data['us-east-1'][0],
        }

        desired_inventory = self.src.generate_inventory()
        self.assertEqual(
            resource_mock.assert_called_with(
                {
                    resource_id: desired_mock_input
                },
            ),
            None,
        )

        self.assertEqual(
            desired_inventory,
            {
                resource_id: resource_mock.return_value
            },
        )


class TestRoute53Source(AWSSourceBaseTestClass, unittest.TestCase):
    '''
    Test the Route53 implementation in the inventory.
    '''

    def setUp(self):
        super().setUp()
        self.source_obj = Route53src

        # Initialize object to test
        source_data = {}
        user_data = {}
        self.src = self.source_obj(source_data, user_data)

        # What data we want to aggregate to our inventory
        self.desired_source_data = {
            'hosted_zones': [
                {
                    'Config': {
                        'Comment': 'This is the description',
                        'PrivateZone': False,
                    },
                    'Id': '/hostedzone/hosted_zone_id',
                    'Name': 'hostedzone.org',
                    'ResourceRecordSetCount': 1,
                    'records': [
                        {
                            'Name': 'record1.clinv.org',
                            'ResourceRecords': [
                                {
                                    'Value': '127.0.0.1'
                                },
                                {
                                    'Value': 'localhost'
                                },
                            ],
                            'TTL': 172800,
                            'Type': 'CNAME'
                        },
                    ],
                },
            ],
        }
        self.desired_user_data = {
            'hosted_zone_id-record1.clinv.org-cname': {
                'description': 'tbd',
                'to_destroy': 'tbd',
                'state': 'active',
            },
        }

        self.src.source_data = self.desired_source_data

    def tearDown(self):
        super().tearDown()

    def test_generate_user_data_creates_empty_user_data_if_no_src_data(self):
        self.src.source_data = {'hosted_zones': {}}
        self.src.generate_user_data()
        self.assertEqual(self.src.user_data, {})

    def test_generate_user_data_adds_desired_default_user_data(self):
        generated_user_data = self.src.generate_user_data()

        self.assertEqual(
            self.src.user_data,
            self.desired_user_data,
        )
        self.assertEqual(
            generated_user_data,
            self.desired_user_data,
        )

    def test_generate_inventory_return_empty_dict_if_no_data(self):
        self.src.source_data = {'hosted_zones': {}}
        self.assertEqual(self.src.generate_inventory(), {})

    @patch('clinv.sources.aws.Route53')
    def test_generate_inventory_creates_expected_dictionary(
        self,
        resource_mock
    ):
        resource_id = 'hosted_zone_id-record1.clinv.org-cname'
        desired_mock_input = {
            'Name': 'record1.clinv.org',
            'ResourceRecords': [
                {
                    'Value': '127.0.0.1'
                },
                {
                    'Value': 'localhost'
                },
            ],
            'TTL': 172800,
            'Type': 'CNAME',
            'description': 'tbd',
            'to_destroy': 'tbd',
            'hosted_zone': {
                'id': '/hostedzone/hosted_zone_id',
                'private': False,
                'name': 'hostedzone.org',
            },
            'state': 'active',
        }
        self.src.user_data = {
            'hosted_zone_id-record1.clinv.org-cname': {
                'description': 'tbd',
                'to_destroy': 'tbd',
                'state': 'active',
            },
        }
        desired_inventory = self.src.generate_inventory()
        self.assertEqual(
            resource_mock.assert_called_with(
                {
                    resource_id: desired_mock_input
                },
            ),
            None,
        )

        self.assertEqual(
            desired_inventory,
            {
                resource_id: resource_mock.return_value
            },
        )


class TestRoute53SourceFetch(AWSSourceBaseTestClass, unittest.TestCase):
    '''
    Extend AWSBaseTewstClass to test the Route53 fetch implementation in the
    inventory.
    '''

    def setUp(self):
        super().setUp()
        self.source_obj = Route53src

        # Initialize object to test
        source_data = {}
        user_data = {}
        self.src = Route53src(source_data, user_data)

        self.boto_client = self.boto.client.return_value

        # Expected boto call to get the hosted zones
        self.boto_client.list_hosted_zones.return_value = {
            'HostedZones': [
                {
                    'CallerReference': 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
                    'Config': {
                        'Comment': 'This is the description',
                        'PrivateZone': False,
                    },
                    'Id': '/hostedzone/hosted_zone_id',
                    'Name': 'hostedzone.org',
                    'ResourceRecordSetCount': 1
                },
            ],
            'IsTruncated': False,
            'MaxItems': '100',
            'ResponseMetadata': {
                'HTTPHeaders': {
                    'content-length': '4211',
                    'content-type': 'text/xml',
                    'date': 'Mon, 15 Jul 2019 13:13:51 GMT',
                    'vary': 'accept-encoding',
                    'x-amzn-requestid': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
                },
                'HTTPStatusCode': 200,
                'RequestId': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                'RetryAttempts': 0,
            },
        }

    def tearDown(self):
        super().tearDown()

    def test_generate_source_data_creates_expected_source_data_attrib(self):
        # Expected boto call to get the resources of a hosted zone
        self.boto_client.list_resource_record_sets.return_value = {
            'IsTruncated': False,
            'MaxItems': '100',
            'ResourceRecordSets': [
                {
                    'Name': 'record1.clinv.org.',
                    'ResourceRecords': [
                        {
                            'Value': '127.0.0.1'
                        },
                        {
                            'Value': 'localhost'
                        },
                    ],
                    'TTL': 172800,
                    'Type': 'CNAME'
                },
            ],
            'ResponseMetadata': {
                'HTTPHeaders': {
                    'content-length': '20952',
                    'content-type': 'text/xml',
                    'date': 'Mon, 15 Jul 2019 13:20:58 GMT',
                    'vary': 'accept-encoding',
                    'x-amzn-requestid': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
                },
                'HTTPStatusCode': 200,
                'RequestId': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                'RetryAttempts': 0
            }
        }

        expected_source_data = {
            'hosted_zones': [
                {
                    'Config': {
                        'Comment': 'This is the description',
                        'PrivateZone': False,
                    },
                    'Id': '/hostedzone/hosted_zone_id',
                    'Name': 'hostedzone.org',
                    'ResourceRecordSetCount': 1,
                    'records': [
                        {
                            'Name': 'record1.clinv.org.',
                            'ResourceRecords': [
                                {
                                    'Value': '127.0.0.1'
                                },
                                {
                                    'Value': 'localhost'
                                },
                            ],
                            'TTL': 172800,
                            'Type': 'CNAME'
                        },
                    ],
                },
            ],
        }

        generated_source_data = self.src.generate_source_data()
        self.assertEqual(
            self.src.source_data,
            expected_source_data,
        )
        self.assertEqual(
            generated_source_data,
            expected_source_data,
        )

    def test_generate_source_data_supports_pagination_on_resources(self):
        self.src.source_data = {'route53': {}}

        expected_first_list_resource_record_sets = {
            'IsTruncated': True,
            'NextRecordName': 'record2.clinv.org',
            'NextRecordType': 'CNAME',
            'MaxItems': '100',
            'ResourceRecordSets': [
                {
                    'Name': 'record1.clinv.org',
                    'ResourceRecords': [
                        {
                            'Value': '127.0.0.1'
                        },
                        {
                            'Value': 'localhost'
                        },
                    ],
                    'TTL': 172800,
                    'Type': 'CNAME'
                },
            ],
            'ResponseMetadata': {
                'HTTPHeaders': {
                    'content-length': '20952',
                    'content-type': 'text/xml',
                    'date': 'Mon, 15 Jul 2019 13:20:58 GMT',
                    'vary': 'accept-encoding',
                    'x-amzn-requestid': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
                },
                'HTTPStatusCode': 200,
                'RequestId': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                'RetryAttempts': 0
            }
        }
        expected_second_list_resource_record_sets = {
            'IsTruncated': False,
            'MaxItems': '100',
            'ResourceRecordSets': [
                {
                    'Name': 'record2.clinv.org',
                    'ResourceRecords': [
                        {
                            'Value': '127.0.0.1'
                        },
                        {
                            'Value': 'localhost'
                        },
                    ],
                    'TTL': 172800,
                    'Type': 'CNAME'
                },
            ],
            'ResponseMetadata': {
                'HTTPHeaders': {
                    'content-length': '20952',
                    'content-type': 'text/xml',
                    'date': 'Mon, 15 Jul 2019 13:20:58 GMT',
                    'vary': 'accept-encoding',
                    'x-amzn-requestid': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
                },
                'HTTPStatusCode': 200,
                'RequestId': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                'RetryAttempts': 0
            }
        }

        self.boto.client.return_value.list_resource_record_sets.side_effect = [
                expected_first_list_resource_record_sets,
                expected_second_list_resource_record_sets,
        ]

        expected_source_data = {
            'hosted_zones': [
                {
                    'Config': {
                        'Comment': 'This is the description',
                        'PrivateZone': False,
                    },
                    'Id': '/hostedzone/hosted_zone_id',
                    'Name': 'hostedzone.org',
                    'ResourceRecordSetCount': 1,
                    'records': [
                        {
                            'Name': 'record1.clinv.org',
                            'ResourceRecords': [
                                {
                                    'Value': '127.0.0.1'
                                },
                                {
                                    'Value': 'localhost'
                                },
                            ],
                            'TTL': 172800,
                            'Type': 'CNAME'
                        },
                        {
                            'Name': 'record2.clinv.org',
                            'ResourceRecords': [
                                {
                                    'Value': '127.0.0.1'
                                },
                                {
                                    'Value': 'localhost'
                                },
                            ],
                            'TTL': 172800,
                            'Type': 'CNAME'
                        },
                    ],
                },
            ],
        }

        self.src.generate_source_data()
        self.assertEqual(
            self.src.source_data,
            expected_source_data,
        )

        self.assertEqual(
            self.boto.client.return_value.list_resource_record_sets.mock_calls,
            [
                call(HostedZoneId='/hostedzone/hosted_zone_id'),
                call(
                    HostedZoneId='/hostedzone/hosted_zone_id',
                    StartRecordName='record2.clinv.org',
                    StartRecordType='CNAME'
                )
            ]
        )


class TestS3Source(AWSSourceBaseTestClass, unittest.TestCase):
    '''
    Test the S3 implementation in the inventory.
    '''

    def setUp(self):
        super().setUp()
        self.source_obj = S3src

        # Initialize object to test
        source_data = {}
        user_data = {}
        self.src = self.source_obj(source_data, user_data)

        # What data we want to aggregate to our inventory
        self.desired_source_data = {
            's3_bucket_name': {
                'CreationDate': datetime.datetime(
                    2012, 12, 12, 0, 7, 46, tzinfo=tzutc()
                ),
                'Name': 's3_bucket_name',
                'permissions': {
                    'READ': 'public',
                    'WRITE': 'private',
                },
                'Grants': [
                    {
                        'Grantee': {
                            'DisplayName': 'admin',
                            'ID': 'admin_id',
                            'Type': 'CanonicalUser'
                        },
                        'Permission': 'READ'
                    },
                    {
                        'Grantee': {
                            'DisplayName': 'admin',
                            'ID': 'admin_id',
                            'Type': 'CanonicalUser'
                        },
                        'Permission': 'WRITE'
                    },
                    {
                        'Grantee': {
                            'Type': 'Group',
                            'URI': 'http://acs.amazonaws.com/'
                                    'groups/global/AllUsers'
                        },
                        'Permission': 'READ'
                    },
                ],
            },
        }
        self.desired_user_data = {
            's3_bucket_name': {
                'description': '',
                'to_destroy': 'tbd',
                'environment': 'tbd',
                'desired_permissions': {
                    'read': 'tbd',
                    'write': 'tbd',
                },
                'state': 'active',
            },
        }

        self.src.source_data = self.desired_source_data

    def tearDown(self):
        super().tearDown()

    def test_generate_source_data_creates_expected_source_data_attrib(self):
        self.boto.client.return_value.list_buckets.return_value = {
            'Buckets': [
                {
                    'CreationDate': datetime.datetime(
                        2012, 12, 12, 0, 7, 46, tzinfo=tzutc()
                    ),
                    'Name': 's3_bucket_name'
                },
            ],
            'Owner': {
                'DisplayName': 'owner_name',
                'ID': 'owner_id'
            },
            'ResponseMetadata': {
                'HTTPHeaders': {'content-type': 'application/xml'},
                'HTTPStatusCode': 200,
                'HostId': 'Host_id',
                'RequestId': 'Request_id',
                'RetryAttempts': 0
            }
        }

        self.boto.client.return_value.get_bucket_acl.return_value = {
            'Grants': [
                {
                    'Grantee': {
                        'DisplayName': 'admin',
                        'ID': 'admin_id',
                        'Type': 'CanonicalUser'
                    },
                    'Permission': 'READ'
                },
                {
                    'Grantee': {
                        'DisplayName': 'admin',
                        'ID': 'admin_id',
                        'Type': 'CanonicalUser'
                    },
                    'Permission': 'WRITE'
                },
                {
                    'Grantee': {
                        'Type': 'Group',
                        'URI':
                            'http://acs.amazonaws.com/groups/global/AllUsers'
                    },
                    'Permission': 'READ'
                },
             ],
            'Owner': {
                'DisplayName': 'owner_name',
                'ID': 'owner_id'
            },
            'ResponseMetadata': {
                'HTTPHeaders': {'content-type': 'application/xml'},
                'HTTPStatusCode': 200,
                'HostId': 'Host_id',
                'RequestId': 'Request_id',
                'RetryAttempts': 0
            }
        }

        self.src.source_data = {}

        generated_source_data = self.src.generate_source_data()

        self.assertEqual(
            self.src.source_data,
            self.desired_source_data,
        )
        self.assertEqual(
            generated_source_data,
            self.desired_source_data,
        )

    def test_generate_user_data_creates_expected_user_data_attrib(self):
        generated_user_data = self.src.generate_user_data()

        self.assertEqual(
            self.src.user_data,
            self.desired_user_data,
        )
        self.assertEqual(
            generated_user_data,
            self.desired_user_data,
        )

    def test_generate_user_data_doesnt_loose_existing_data(self):
        user_key = [key for key in self.desired_user_data.keys()][0]
        desired_user_data = {user_key: {}}
        self.src.user_data = desired_user_data

        self.src.generate_user_data()

        self.assertEqual(
            self.src.user_data,
            desired_user_data,
        )

    def test_generate_inventory_return_empty_dict_if_no_data(self):
        self.src.source_data = {}
        self.assertEqual(self.src.generate_inventory(), {})

    @patch('clinv.sources.aws.S3')
    def test_generate_inventory_creates_expected_dictionary(
        self,
        resource_mock
    ):
        resource_id = 's3_bucket_name'
        self.src.user_data = self.desired_user_data

        desired_mock_input = {
            **self.src.user_data[resource_id],
            **self.src.source_data[resource_id],
        }

        desired_inventory = self.src.generate_inventory()
        self.assertEqual(
            resource_mock.assert_called_with(
                {
                    resource_id: desired_mock_input
                },
            ),
            None,
        )

        self.assertEqual(
            desired_inventory,
            {
                resource_id: resource_mock.return_value
            },
        )


class TestIAMUserSource(AWSSourceBaseTestClass, unittest.TestCase):
    '''
    Test the IAMUser source implementation in the inventory.
    '''

    def setUp(self):
        super().setUp()
        self.source_obj = IAMUsersrc

        # Initialize object to test
        source_data = {}
        user_data = {}
        self.src = self.source_obj(source_data, user_data)

        # What data we want to aggregate to our inventory
        self.desired_source_data = {
            'arn:aws:iam::XXXXXXXXXXXX:user/user_1': {
                'Path': '/',
                'CreateDate': datetime.datetime(
                    2019, 2, 7, 12, 15, 57, tzinfo=tzutc()
                ),
                'UserId': 'XXXXXXXXXXXXXXXXXXXXX',
                'UserName': 'User 1'
            },
        }
        self.desired_user_data = {
            'arn:aws:iam::XXXXXXXXXXXX:user/user_1': {
                'name': 'User 1',
                'description': 'tbd',
                'to_destroy': 'tbd',
                'state': 'tbd',
            },
        }

        self.src.source_data = self.desired_source_data

    def tearDown(self):
        super().tearDown()

    def test_generate_source_data_creates_expected_source_data_attrib(self):
        self.boto.client.return_value.list_users.return_value = {
            'Users': [
                {
                    'UserName': 'User 1',
                    'Path': '/',
                    'CreateDate': datetime.datetime(
                        2019, 2, 7, 12, 15, 57, tzinfo=tzutc()
                    ),
                    'PasswordLastUsed': datetime.datetime(
                        2019, 11, 5, 9, 10, 59, tzinfo=tzutc()
                    ),
                    'UserId': 'XXXXXXXXXXXXXXXXXXXXX',
                    'Arn': 'arn:aws:iam::XXXXXXXXXXXX:user/user_1'
                },
            ]
        }

        self.src.source_data = {}
        generated_source_data = self.src.generate_source_data()

        self.assertEqual(
            self.src.source_data,
            self.desired_source_data,
        )
        self.assertEqual(
            generated_source_data,
            self.desired_source_data,
        )

    def test_generate_user_data_creates_expected_user_data_attrib(self):
        generated_user_data = self.src.generate_user_data()

        self.assertEqual(
            self.src.user_data,
            self.desired_user_data,
        )
        self.assertEqual(
            generated_user_data,
            self.desired_user_data,
        )

    def test_generate_user_data_doesnt_loose_existing_data(self):
        desired_user_data = {
            'arn:aws:iam::XXXXXXXXXXXX:user/user_1': {
                'name': 'User 1',
                'description': 'User 1 description',
                'to_destroy': False,
            },
        }

        self.src.user_data = desired_user_data

        self.src.generate_user_data()

        self.assertEqual(
            self.src.user_data,
            desired_user_data,
        )

    def test_generate_inventory_return_empty_dict_if_no_data(self):
        self.src.source_data = {}
        self.assertEqual(self.src.generate_inventory(), {})

    @patch('clinv.sources.aws.IAMUser')
    def test_generate_inventory_creates_expected_dictionary(
        self,
        resource_mock
    ):
        resource_id = 'arn:aws:iam::XXXXXXXXXXXX:user/user_1'
        self.src.user_data = self.desired_user_data

        desired_mock_input = {
            **self.src.user_data[resource_id],
            **self.src.source_data[resource_id],
        }

        desired_inventory = self.src.generate_inventory()
        self.assertEqual(
            resource_mock.assert_called_with(
                {
                    resource_id: desired_mock_input
                },
            ),
            None,
        )

        self.assertEqual(
            desired_inventory,
            {
                resource_id: resource_mock.return_value
            },
        )


class TestIAMGroupSource(AWSSourceBaseTestClass, unittest.TestCase):
    '''
    Test the IAMGroup implementation in the inventory.
    '''

    def setUp(self):
        super().setUp()
        self.source_obj = IAMGroupsrc

        # Initialize object to test
        source_data = {}
        user_data = {}
        self.src = self.source_obj(source_data, user_data)

        # What data we want to aggregate to our inventory
        self.desired_source_data = {
            'arn:aws:iam::XXXXXXXXXXXX:group/Administrator': {
                'CreateDate': datetime.datetime(
                    2019, 11, 4, 12, 41, 24, tzinfo=tzutc()
                ),
                'GroupId': 'XXXXXXXXXXXXXXXXXXXXX',
                'GroupName': 'Administrator',
                'Path': '/',
                'Users': [
                    'arn:aws:iam::XXXXXXXXXXXX:user/user_1'
                ],
                'InlinePolicies': [
                    'arn:aws:iam::aws:policy/Inlinepolicy'
                ],
                'AttachedPolicies': [
                    'arn:aws:iam::aws:policy/Attachedpolicy'
                ],
            },
        }
        self.desired_user_data = {
            'arn:aws:iam::XXXXXXXXXXXX:group/Administrator': {
                'name': 'Administrator',
                'description': 'tbd',
                'to_destroy': 'tbd',
                'state': 'tbd',
                'desired_users': [
                    'arn:aws:iam::XXXXXXXXXXXX:user/user_1'
                ]
            },
        }

        self.src.source_data = self.desired_source_data

    def tearDown(self):
        super().tearDown()

    def test_generate_source_data_creates_expected_source_data_attrib(self):
        boto_mock = self.boto.client.return_value
        boto_mock.list_groups.return_value = {
            'Groups': [
                {
                    'Arn': 'arn:aws:iam::XXXXXXXXXXXX:group/Administrator',
                    'CreateDate': datetime.datetime(
                        2019, 11, 4, 12, 41, 24, tzinfo=tzutc()
                    ),
                    'GroupId': 'XXXXXXXXXXXXXXXXXXXXX',
                    'GroupName': 'Administrator',
                    'Path': '/',
                }
            ],
            'IsTruncated': False,
            'ResponseMetadata': {},
        }

        boto_mock.get_group.return_value = {
            'Group': {
                'Arn': 'arn:aws:iam::XXXXXXXXXXXX:group/Administrator',
                'CreateDate': datetime.datetime(
                    2019, 11, 4, 12, 41, 24, tzinfo=tzutc()
                ),
                'GroupId': 'XXXXXXXXXXXXXXXXXXXXX',
                'GroupName': 'Administrator',
                'Path': '/',
            },
            'IsTruncated': False,
            'ResponseMetadata': {},
            'Users': [
                {
                    'UserName': 'User 1',
                    'Path': '/',
                    'CreateDate': datetime.datetime(
                        2019, 2, 7, 12, 15, 57, tzinfo=tzutc()
                    ),
                    'PasswordLastUsed': datetime.datetime(
                        2019, 11, 5, 9, 10, 59, tzinfo=tzutc()
                    ),
                    'UserId': 'XXXXXXXXXXXXXXXXXXXXX',
                    'Arn': 'arn:aws:iam::XXXXXXXXXXXX:user/user_1'
                }
            ],
        }
        boto_mock.list_group_policies.return_value = {
            'PolicyNames': [
                {
                    'PolicyArn': 'arn:aws:iam::aws:policy/Inlinepolicy',
                    'PolicyName': 'InlinePolicy'
                },
            ],
            'IsTruncated': False,
            'ResponseMetadata': {},
        }
        boto_mock.list_attached_group_policies.return_value = {
            'AttachedPolicies': [
                {
                    'PolicyArn': 'arn:aws:iam::aws:policy/Attachedpolicy',
                    'PolicyName': 'AttachedPolicy'
                },
            ],
            'IsTruncated': False,
            'ResponseMetadata': {},
        }

        self.src.source_data = {}

        generated_source_data = self.src.generate_source_data()

        self.assertEqual(
            self.src.source_data,
            self.desired_source_data,
        )
        self.assertEqual(
            generated_source_data,
            self.desired_source_data,
        )

    def test_generate_user_data_creates_expected_user_data_attrib(self):
        generated_user_data = self.src.generate_user_data()

        self.assertEqual(
            self.src.user_data,
            self.desired_user_data,
        )
        self.assertEqual(
            generated_user_data,
            self.desired_user_data,
        )

    def test_generate_user_data_doesnt_loose_existing_data(self):
        user_key = [key for key in self.desired_user_data.keys()][0]
        desired_user_data = {user_key: {}}
        self.src.user_data = desired_user_data

        self.src.generate_user_data()

        self.assertEqual(
            self.src.user_data,
            desired_user_data,
        )

    def test_generate_inventory_return_empty_dict_if_no_data(self):
        self.src.source_data = {}
        self.assertEqual(self.src.generate_inventory(), {})

    @patch('clinv.sources.aws.IAMGroup')
    def test_generate_inventory_creates_expected_dictionary(
        self,
        resource_mock
    ):
        resource_id = 'arn:aws:iam::XXXXXXXXXXXX:group/Administrator'
        self.src.user_data = self.desired_user_data

        desired_mock_input = {
            **self.src.user_data[resource_id],
            **self.src.source_data[resource_id],
        }

        desired_inventory = self.src.generate_inventory()
        self.assertEqual(
            resource_mock.assert_called_with(
                {
                    resource_id: desired_mock_input
                },
            ),
            None,
        )

        self.assertEqual(
            desired_inventory,
            {
                resource_id: resource_mock.return_value
            },
        )


class ClinvAWSResourceTests(ClinvGenericResourceTests):
    '''Must be combined with a unittest.TestCase that defines:
        * self.resource as a ClinvAWSResource subclass instance
        * self.raw as a dictionary with the data of the resource
        * self.id as a string with the resource id

    And the following properties must be set:
        * resource name: resource_name
        * security groups: ['sg-f2234gf6', 'sg-cwfccs17']
        * type: 'c4.4xlarge'
        * region: 'us-east-1'
    '''

    def setUp(self):
        self.module_name = 'aws'
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def test_get_security_groups(self):
        self.assertEqual(
            self.resource.security_groups,
            ['sg-f2234gf6', 'sg-cwfccs17']
        )

    def test_get_type(self):
        self.assertEqual(self.resource.type, 'c4.4xlarge')

    def test_get_region(self):
        self.assertEqual(
            self.resource.region,
            'us-east-1',
        )

    def test_search_by_security_group(self):
        self.assertTrue(self.resource.search('sg-f2234gf6'))

    def test_search_by_region(self):
        self.assertTrue(self.resource.search('us-east-1'))

    def test_search_by_type(self):
        self.assertTrue(self.resource.search('c4.4xlarge'))


class TestEC2(ClinvAWSResourceTests, unittest.TestCase):
    def setUp(self):
        super().setUp()

        self.id = 'i-01'
        self.raw = {
            'i-01': {
                'AmiLaunchIndex': 0,
                'Architecture': 'x86_64',
                'BlockDeviceMappings': [
                    {
                        'DeviceName': '/dev/sda1',
                        'Ebs': {
                            'AttachTime': datetime.datetime(
                                2018, 5, 10, 2, 58, 4,
                                tzinfo=tzutc()
                            ),
                            'DeleteOnTermination': True,
                            'Status': 'attached',
                            'VolumeId': 'vol-02257f9299430042f'
                        }
                    }
                ],
                'CapacityReservationSpecification': {
                    'CapacityReservationPreference': 'open'
                },
                'ClientToken': '',
                'CpuOptions': {
                    'CoreCount': 8,
                    'ThreadsPerCore': 2
                },
                'EbsOptimized': True,
                'HibernationOptions': {'Configured': False},
                'Hypervisor': 'xen',
                'ImageId': 'ami-ffcsssss',
                'InstanceId': 'i-01',
                'InstanceType': 'c4.4xlarge',
                'KeyName': 'ssh_keypair',
                'LaunchTime': datetime.datetime(
                    2018, 5, 10, 7, 13, 17, tzinfo=tzutc()
                ),
                'Monitoring': {'State': 'enabled'},
                'NetworkInterfaces': [
                    {
                        'Association': {
                            'IpOwnerId': '585394229490',
                            'PublicDnsName': 'ec2.aws.com',
                            'PublicIp': '32.312.444.22'
                        },
                        'Attachment': {
                            'AttachTime': datetime.datetime(
                                2018, 5, 10, 2, 58, 3,
                                tzinfo=tzutc()
                            ),
                            'AttachmentId': 'eni-032346',
                            'DeleteOnTermination': True,
                            'DeviceIndex': 0,
                            'Status': 'attached'
                        },
                        'Description': 'Primary ni',
                        'Groups': [
                            {
                                'GroupId': 'sg-f2234gf6',
                                'GroupName': 'sg-1'
                            },
                            {
                                'GroupId': 'sg-cwfccs17',
                                'GroupName': 'sg-2'
                            }
                        ],
                        'InterfaceType': 'interface',
                        'Ipv6Addresses': [],
                        'MacAddress': '0a:ff:ff:ff:ff:aa',
                        'NetworkInterfaceId': 'eni-3fssaw0a',
                        'OwnerId': '583949112399',
                        'PrivateDnsName': 'ipec2.internal',
                        'PrivateIpAddress': '142.33.2.113',
                        'PrivateIpAddresses': [
                            {
                                'Association': {
                                    'IpOwnerId': '584460090',
                                    'PublicDnsName': 'ec2.com',
                                    'PublicIp': '32.312.444.22'
                                },
                                'Primary': True,
                                'PrivateDnsName': 'ecernal',
                                'PrivateIpAddress':
                                    '142.33.2.113',
                            }
                        ],
                        'SourceDestCheck': True,
                        'Status': 'in-use',
                        'SubnetId': 'subnet-3ssaafs1',
                        'VpcId': 'vpc-fs12f872'
                    }
                ],
                'Placement': {
                    'AvailabilityZone': 'eu-east-1a',
                    'GroupName': '',
                    'Tenancy': 'default'
                },
                'PrivateDnsName': 'ip-112.ec2.internal',
                'PrivateIpAddress': '142.33.2.113',
                'ProductCodes': [],
                'PublicDnsName': 'ec2.com',
                'PublicIpAddress': '32.312.444.22',
                'RootDeviceName': '/dev/sda1',
                'RootDeviceType': 'ebs',
                'SecurityGroups': [
                    {
                        'GroupId': 'sg-f2234gf6',
                        'GroupName': 'sg-1'
                    },
                    {
                        'GroupId': 'sg-cwfccs17',
                        'GroupName': 'sg-2'
                    }
                ],
                'SourceDestCheck': True,
                'State': {'Code': 16, 'Name': 'active'},
                'StateTransitionReason': 'reason',
                'SubnetId': 'subnet-sfsdwf12',
                'Tags': [
                    {'Key': 'Name', 'Value': 'resource_name'}
                ],
                'VirtualizationType': 'hvm',
                'VpcId': 'vpc-31084921',
                'description': 'This is in the description of the instance',
                'region': 'us-east-1',
                'to_destroy': 'tbd',
                'environment': 'tbd',
            }
        }
        self.resource = EC2(self.raw)

    def tearDown(self):
        super().tearDown()

    def test_get_instance_name_return_null_if_empty(self):
        self.raw['i-01'].pop('Tags', None)
        self.assertEqual(self.resource.name, 'none')

    def test_get_private_ip(self):
        self.assertEqual(self.resource.private_ips, ['142.33.2.113'])

    def test_get_multiple_private_ips(self):
        self.resource.raw['NetworkInterfaces'][0]['PrivateIpAddresses'].append(
            {
                'PrivateIpAddress':  '142.33.2.114',
            }

        )
        self.assertEqual(
            self.resource.private_ips,
            ['142.33.2.113', '142.33.2.114']
        )

    def test_get_public_ip(self):
        self.assertEqual(self.resource.public_ips, ['32.312.444.22'])

    def test_get_multiple_public_ips(self):
        self.resource.raw['NetworkInterfaces'][0]['PrivateIpAddresses'].append(
            {
                'Association': {
                    'PublicIp': '32.312.444.23'

                }
            }

        )
        self.assertEqual(
            self.resource.public_ips,
            ['32.312.444.22', '32.312.444.23']
        )

    def test_get_state_transition_reason(self):
        self.assertEqual(self.resource.state_transition, 'reason')

    def test_print_resource_information(self):
        self.resource.raw['State']['Name'] = 'running'

        self.resource.print()
        print_calls = (
            call('i-01'),
            call('  Name: resource_name'),
            call('  State: running'),
            call('  Type: c4.4xlarge'),
            call("  SecurityGroups: ['sg-f2234gf6', 'sg-cwfccs17']"),
            call("  PrivateIP: ['142.33.2.113']"),
            call("  PublicIP: ['32.312.444.22']"),
        )

        for print_call in print_calls:
            self.assertIn(print_call, self.print.mock_calls)
        self.assertEqual(7, len(self.print.mock_calls))

    def test_print_ec2_reason_if_stopped(self):
        self.raw['i-01']['State']['Name'] = 'stopped'
        self.resource.print()
        print_calls = (
            call('i-01'),
            call('  Name: resource_name'),
            call('  State: stopped'),
            call('  State Reason: reason'),
            call('  Type: c4.4xlarge'),
            call("  SecurityGroups: ['sg-f2234gf6', 'sg-cwfccs17']"),
            call("  PrivateIP: ['142.33.2.113']"),
            call("  PublicIP: ['32.312.444.22']"),
        )

        for print_call in print_calls:
            self.assertIn(print_call, self.print.mock_calls)
        self.assertEqual(8, len(self.print.mock_calls))

    def test_search_ec2_by_public_ip(self):
        self.assertTrue(self.resource.search('32.312.444.22'))

    def test_search_ec2_by_private_ip(self):
        self.assertTrue(self.resource.search('142.33.2.113'))


class TestRDS(ClinvAWSResourceTests, unittest.TestCase):
    def setUp(self):
        super().setUp()

        self.id = 'db-YDFL2'
        self.raw = {
            'db-YDFL2': {
                'AllocatedStorage': 100,
                'AssociatedRoles': [],
                'AutoMinorVersionUpgrade': True,
                'AvailabilityZone': 'us-east-1a',
                'BackupRetentionPeriod': 7,
                'CACertificateIdentifier': 'rds-ca-2015',
                'DBInstanceArn': 'arn:aws:rds:us-east-1:224119285:db:db',
                'DBInstanceClass': 'c4.4xlarge',
                'DBInstanceIdentifier': 'resource_name',
                'DBInstanceStatus': 'active',
                'DBSecurityGroups': ['sg-f2234gf6', 'sg-cwfccs17'],
                'DBSubnetGroup': {
                    'DBSubnetGroupDescription': 'Created from the RDS '
                    'Management Console',
                    'DBSubnetGroupName': 'default-vpc-v2dcp2jh',
                    'SubnetGroupStatus': 'Complete',
                    'Subnets': [
                        {
                            'SubnetAvailabilityZone': {
                                'Name': 'us-east-1a'
                            },
                            'SubnetIdentifier': 'subnet-42sfl222',
                            'SubnetStatus': 'Active'
                        },
                        {
                            'SubnetAvailabilityZone': {
                                'Name': 'us-east-1e'
                            },
                            'SubnetIdentifier': 'subnet-42sfl221',
                            'SubnetStatus': 'Active'
                        },
                    ],
                    'VpcId': 'vpc-v2dcp2jh'},
                'DbiResourceId': 'db-YDFL2',
                'DeletionProtection': True,
                'Endpoint': {
                    'Address': 'rds-name.us-east-1.rds.amazonaws.com',
                    'HostedZoneId': '202FGHSL2JKCFW',
                    'Port': 5521
                },
                'Engine': 'mariadb',
                'EngineVersion': '1.2',
                'InstanceCreateTime': datetime.datetime(
                    2019, 6, 17, 15, 15, 8, 461000, tzinfo=tzutc()
                ),
                'Iops': 1000,
                'MasterUsername': 'root',
                'MultiAZ': True,
                'PreferredBackupWindow': '03:00-04:00',
                'PreferredMaintenanceWindow': 'fri:04:00-fri:05:00',
                'PubliclyAccessible': False,
                'StorageEncrypted': True,
                'description': 'This is in the description of the instance',
                'region': 'us-east-1',
                'to_destroy': 'tbd',
                'environment': 'production',
            }
        }
        self.resource = RDS(self.raw)

    def tearDown(self):
        super().tearDown()

    def test_print_resource_information(self):
        self.resource.print()
        print_calls = (
            call('db-YDFL2'),
            call('  Name: resource_name'),
            call('  Type: c4.4xlarge'),
            call('  Description: This is in the description of the instance'),
        )

        for print_call in print_calls:
            self.assertIn(print_call, self.print.mock_calls)
        self.assertEqual(4, len(self.print.mock_calls))


class TestRoute53(ClinvGenericResourceTests, unittest.TestCase):
    def setUp(self):
        self.module_name = 'aws'
        super().setUp()

        self.id = 'hosted_zone_id-record1.clinv.org-cname'
        self.raw = {
            'hosted_zone_id-record1.clinv.org-cname': {
                'Name': 'record1.clinv.org',
                'ResourceRecords': [
                    {
                        'Value': '127.0.0.1'
                    },
                    {
                        'Value': 'localhost'
                    },
                ],
                'TTL': 172800,
                'Type': 'CNAME',
                'description': 'This is the description',
                'to_destroy': 'tbd',
                'state': 'active',
                'hosted_zone': {
                    'id': '/hostedzone/hosted_zone_id',
                    'private': False,
                    'name': 'hostedzone.org',
                },
            },
        }
        self.resource = Route53(self.raw)

    def tearDown(self):
        super().tearDown()

    def test_name_property_works_as_expected(self):
        '''
        Override the parent test, as the name == id
        '''

        self.assertEqual(self.resource.name, 'record1.clinv.org')

    def test_search_resource_by_regexp_on_name(self):
        '''
        Override the parent test, as the name == id
        '''

        self.assertTrue(self.resource.search('.*record1'))

    def test_short_print_resource_information(self):
        '''
        Override the parent test, as the name == id
        '''

        self.resource.short_print()

        self.assertEqual(
            self.print.assert_called_with(self.resource.id),
            None,
        )

    def test_value_property_works_as_expected(self):
        self.assertEqual(self.resource.value, ['127.0.0.1', 'localhost'])

    def test_value_property_supports_aliases(self):
        self.raw = {
            'record1.clinv.org': {
                'Name': 'record1.clinv.org',
                'AliasTarget': {
                    'DNSName': 'aliasdns.org',
                    'EvaluateTargetHealth': False,
                    'HostedZoneId': 'XXXXXXXXXXXXXX'
                },
                'TTL': 172800,
                'Type': 'A',
                'description': 'This is the description',
                'to_destroy': 'tbd',
                'state': 'active',
                'hosted_zone': {
                    'id': '/hostedzone/hosted_zone_id',
                    'private': False,
                    'name': 'hostedzone.org',
                },
            },
        }
        self.resource = Route53(self.raw)
        self.assertEqual(self.resource.value, ['aliasdns.org'])

    def test_type_property_works_as_expected(self):
        self.assertEqual(self.resource.type, 'CNAME')

    def test_to_destroy_property_works_as_expected(self):
        self.assertEqual(self.resource.to_destroy, 'tbd')

    def test_hosted_zone_property_works_as_expected(self):
        self.assertEqual(self.resource.hosted_zone, 'hostedzone.org')

    def test_hosted_zone_id_property_works_as_expected(self):
        self.assertEqual(
            self.resource.hosted_zone_id,
            '/hostedzone/hosted_zone_id',
        )

    def test_access_property_works_as_expected_if_public(self):
        self.assertEqual(self.resource.access, 'public')

    def test_access_property_works_as_expected_if_private(self):
        self.resource.raw['hosted_zone']['private'] = True
        self.assertEqual(self.resource.access, 'private')

    def test_print_resource_information(self):
        self.resource.print()
        print_calls = (
            call('hosted_zone_id-record1.clinv.org-cname'),
            call('  Name: record1.clinv.org'),
            call('  Value:'),
            call('    127.0.0.1'),
            call('    localhost'),
            call('  Type: CNAME'),
            call('  Zone: /hostedzone/hosted_zone_id'),
            call('  Access: public'),
            call('  Description: This is the description'),
            call('  Destroy: tbd'),
        )

        for print_call in print_calls:
            self.assertIn(print_call, self.print.mock_calls)
        self.assertEqual(10, len(self.print.mock_calls))

    def test_search_resource_by_regexp_on_value(self):
        self.assertTrue(self.resource.search('.*alhost'))

    def test_search_resource_by_type(self):
        self.assertTrue(self.resource.search('CNAME'))

    def test_search_resource_by_type_insensitive(self):
        self.assertTrue(self.resource.search('cname'))


class TestS3(ClinvGenericResourceTests, unittest.TestCase):
    def setUp(self):
        self.module_name = 'aws'
        super().setUp()

        self.id = 's3_bucket_name'
        self.raw = {
            's3_bucket_name': {
                'CreationDate': datetime.datetime(
                    2012, 12, 12, 0, 7, 46, tzinfo=tzutc()
                ),
                'Name': 'resource_name',
                'permissions': {
                    'READ': 'public',
                    'WRITE': 'private',
                },
                'Grants': [
                    {
                        'Grantee': {
                            'DisplayName': 'admin',
                            'ID': 'admin_id',
                            'Type': 'CanonicalUser'
                        },
                        'Permission': 'READ'
                    },
                    {
                        'Grantee': {
                            'DisplayName': 'admin',
                            'ID': 'admin_id',
                            'Type': 'CanonicalUser'
                        },
                        'Permission': 'WRITE'
                    },
                    {
                        'Grantee': {
                            'Type': 'Group',
                            'URI': 'http://acs.amazonaws.com/'
                                    'groups/global/AllUsers'
                        },
                        'Permission': 'READ'
                    },
                ],
                'description': 'This is the description',
                'to_destroy': 'tbd',
                'environment': 'tbd',
                'desired_permissions': {
                    'read': 'tbd',
                    'write': 'tbd',
                },
                'state': 'active',
            },
        }
        self.resource = S3(self.raw)

    def tearDown(self):
        super().tearDown()

    def test_to_destroy_property_works_as_expected(self):
        self.assertEqual(self.resource.to_destroy, 'tbd')

    def test_print_resource_information(self):
        self.resource.print()
        print_calls = (
            call('s3_bucket_name'),
            call('  Description: This is the description'),
            call('  Permissions: desired/real'),
            call('      READ: tbd/public'),
            call('      WRITE: tbd/private'),
            call('  Environment: tbd'),
            call('  State: active'),
        )

        for print_call in print_calls:
            self.assertIn(print_call, self.print.mock_calls)
        self.assertEqual(8, len(self.print.mock_calls))


class TestIAMGroup(ClinvGenericResourceTests, unittest.TestCase):
    def setUp(self):
        self.module_name = 'aws'
        super().setUp()

        self.id = 'arn:aws:iam::XXXXXXXXXXXX:group/Administrator'
        self.raw = {
            'arn:aws:iam::XXXXXXXXXXXX:group/Administrator': {
                'CreateDate': datetime.datetime(
                    2019, 11, 4, 12, 41, 24, tzinfo=tzutc()
                ),
                'GroupId': 'XXXXXXXXXXXXXXXXXXXXX',
                'GroupName': 'resource_name',
                'Path': '/',
                'Users': [
                    'arn:aws:iam::XXXXXXXXXXXX:user/user_1'
                ],
                'InlinePolicies': [
                    'arn:aws:iam::aws:policy/Inlinepolicy'
                ],
                'AttachedPolicies': [
                    'arn:aws:iam::aws:policy/Attachedpolicy'
                ],
                'description': 'This is the description',
                'state': 'active',
                'to_destroy': 'tbd',
                'desired_users': [
                    'arn:aws:iam::XXXXXXXXXXXX:user/user_2'
                ]
            },
        }
        self.resource = IAMGroup(self.raw)

    def tearDown(self):
        super().tearDown()

    def test_users_property_works_as_expected(self):
        self.assertEqual(
            self.resource.users,
            ['arn:aws:iam::XXXXXXXXXXXX:user/user_1']
        )

    def test_desired_users_property_works_as_expected(self):
        self.assertEqual(
            self.resource.desired_users,
            ['arn:aws:iam::XXXXXXXXXXXX:user/user_2']
        )

    def test_desired_inline_policies_property_works_as_expected(self):
        self.assertEqual(
            self.resource.inline_policies,
            ['arn:aws:iam::aws:policy/Inlinepolicy']
        )

    def test_desired_attached_policies_property_works_as_expected(self):
        self.assertEqual(
            self.resource.attached_policies,
            ['arn:aws:iam::aws:policy/Attachedpolicy']
        )

    def test_search_by_users_in_group(self):
        self.assertTrue(self.resource.search('.*user_1'))

    def test_search_by_desired_users_in_group(self):
        self.assertTrue(self.resource.search('.*user_2'))

    def test_search_by_inline_policies_in_group(self):
        self.assertTrue(self.resource.search('.*Inlinepolicy'))

    def test_search_by_attached_policies_in_group(self):
        self.assertTrue(self.resource.search('.*Attachedpolicy'))

    def test_print_resource_information(self):
        self.resource.print()
        print_calls = (
            call('arn:aws:iam::XXXXXXXXXXXX:group/Administrator'),
            call('  Name: resource_name'),
            call('  Description: This is the description'),
            call('  Users:'),
            call('    - arn:aws:iam::XXXXXXXXXXXX:user/user_1'),
            call('  AttachedPolicies:'),
            call('    - arn:aws:iam::aws:policy/Attachedpolicy'),
            call('  InlinePolicies:'),
            call('    - arn:aws:iam::aws:policy/Inlinepolicy'),
            call('  State: active'),
            call('  Destroy: tbd'),
        )

        for print_call in print_calls:
            self.assertIn(print_call, self.print.mock_calls)
        self.assertEqual(11, len(self.print.mock_calls))


class TestIAMUser(ClinvGenericResourceTests, unittest.TestCase):
    def setUp(self):
        self.module_name = 'aws'
        super().setUp()

        self.id = 'arn:aws:iam::XXXXXXXXXXXX:user/user_1'
        self.raw = {
            'arn:aws:iam::XXXXXXXXXXXX:user/user_1': {
                'Path': '/',
                'CreateDate': datetime.datetime(
                    2019, 2, 7, 12, 15, 57, tzinfo=tzutc()
                ),
                'UserId': 'XXXXXXXXXXXXXXXXXXXXX',
                'Arn': 'arn:aws:iam::XXXXXXXXXXXX:user/user_1',
                'name': 'resource_name',
                'description': 'This is the description',
                'state': 'active',
                'to_destroy': 'tbd',
            },
        }
        self.resource = IAMUser(self.raw)

    def tearDown(self):
        super().tearDown()

    def test_print_resource_information(self):
        self.resource.print()
        print_calls = (
            call('arn:aws:iam::XXXXXXXXXXXX:user/user_1'),
            call('  Name: resource_name'),
            call('  Description: This is the description'),
            call('  State: active'),
            call('  Destroy: tbd'),
        )

        for print_call in print_calls:
            self.assertIn(print_call, self.print.mock_calls)
        self.assertEqual(5, len(self.print.mock_calls))
